[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd packages/backend && npm install"]

[phases.build]
cmds = ["cd packages/backend && npm run build"]

[start]
cmd = "cd packages/backend && npm run start:prod"
